# Generated by Django 5.0.4 on 2024-05-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0010_order_paid_order_pyment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
